### ISSUE TITLE
Regeln: Schlösser knacken

### ISSUE THREAD

**Issue by okin** [okin/shadowrun-notizen#5]
Schlosser + Geschick

Wie mit bestimmter Schlossstufe umgehen?

**Comment by onnlinetool** [comment]
Downloaden Knack  Downloaden Knack  Downloaden Knack

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw
